name = "voice-clone-showcase"
pages_build_output_dir = ".open-next/assets"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "VOTES"
id = "fba90fd25a414c029e22ddc876a2a79c"